### PR TITLE
Use pip-tools

### PR DESCRIPTION
**Pull request by lfdebrux**
Ticket: https://trello.com/c/iLQca47V/251-replace-custom-script-to-freeze-requirements-with-pip-tools

I missed this one earlier.

We want to remove our custom freeze-requirements script from dmutils; this PR replaces its use with pip-tools.

This repo is a bit more convoluted unfortunately, as we have to downgrade Flask to avoid conflicts with the requirements of digitalmarketplace-utils, and upgrade moto to a pre-release version to avoid conflicts with idna.

I also took a different approach with freezing, keeping around the original `requirements*.txt` files when running `pip-compile`. This meant that the versions specified there were used as inputs to the dependency resolution algorithm and we ended up with the same versions of all requirements in almost all cases.

### CODE REVIEW

**Comment by katstevens** [comment]
Some odd test failures here?

**Comment by lfdebrux** [comment]
> Some odd test failures here?

I'm a bit stumped by them. They go away if you downgrade `moto`, but does that mean they are real errors and the older version of `moto` just doesn't raise them? 🤷‍♂ Need to look into it more

**Comment by lfdebrux** [comment]
> > Some odd test failures here?
> 
> I'm a bit stumped by them. They go away if you downgrade `moto`, but does that mean they are real errors and the older version of `moto` just doesn't raise them? 🤷‍♂ I need to look into it more.

Looks like the way around this is to stick with moto==1.3.7.

**Comment by lfdebrux** [comment]
Tests passing, this is ready for review 🎉

**Pull request merged**
