### PR TITLE
add custom virus definition file to catch the eicar test signature as a substring

### PR DESCRIPTION
**Pull request by risicle**
https://trello.com/c/WnQGJGBi

clamav's main definitions can't be relied upon to keep reacting to eicar in the same way, and recently seem to have stopped detecting it when used as a file substring. So we add a supplementary definition file to ensure our smoulder tests will behave as we expect. Definition file is stored in two parts which get XOR'ed together as it contains a representation of the signature itself and we don't want to trigger naive scanners everywhere we go with this repo.

For bonus points, we _could_ assemble the file at runtime instead of build time so we don't store the final string in our docker images either.

Added the string `Eicar-Test-Signature.UNOFFICIAL` to `DM_EICAR_TEST_SIGNATURE_RESULT_STRINGS` as this is how it now appears when using the custom def.

### CODE REVIEW

**Comment by katstevens** [comment]
> for bonus points, we could assemble the file at runtime instead of build time so we don't store the final string in our docker images either

I like this idea? What would need to change?

**Comment by risicle** [comment]
I'd probably have to wrap the `clamd` called by `supervisord` in a shell script the same we do with other daemons.

**Comment by lfdebrux** [comment]
What happens if ClamAV decide to reintroduce the EICAR signature into their definitions? Will this change interfere in any way do you think?

**Comment by risicle** [comment]
It _shouldn't_ - this is why I've kept both of the existing strings it was identified as in DM_EICAR_TEST_SIGNATURE_RESULT_STRINGS.

**Comment by lfdebrux** [comment]
@risicle if you've got a Docker image on DockerHub I can pull it and see whether Snyk complains about the presence of EICAR.

**Comment by risicle** [comment]
Oh that's an idea, there's an image up with the same tag name as this branch name - though I think we might be running out of snyk credits on our dmp organization.

**Comment by lfdebrux** [comment]
> Oh that's an idea, there's an image up with the same tag name as this branch name - though I think we might be running out of snyk credits on our dmp organization.

No difference in the number of vulnerabilities for this image, as compared to the image tagged as latest on DockerHub.

**Comment by risicle** [comment]
Not sure snyk does any form of "virus scan" at all tbh.

**Pull request merged**
